### ISSUE TITLE
Change navigation

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/docs.kuadrant.io#15]
Based on conversation here, update docs navigation

```
Overview (what is currently shown in Getting Started link)
Getting Started
  - Quick Start
  - Install
Concepts and APIs
   - Gateways
   - DNSPolicy
   - TLSPolicy
   - RateLimitPolicy
   - AuthPolicy
Experimental
    - E/W stuff
Components
   - MCG
   - Authorino 
    ...

```

**Comment by jasonmadigan** [comment]
Just going to focus on the nav changes. Getting Started guide (multicluster-gateway-controller/docs/getting-started.md) may need some edits because of its new home, outside of MGC - but will create a follow-on issue for this. 

Plan to move multicluster-gateway-controller/docs/getting-started.md into index.md in this repo, as seeingly there's no way to tell mkdocs the index or `/` route is in a doc that's in another repo.

**Comment by maleck13** [comment]
@jasonmadigan can you ensure to bring that issue up the backlog so it gets discussed at planning

**Comment by jasonmadigan** [comment]
@maleck13 yep

**Comment by jasonmadigan** [comment]
I made some edits in https://docs.kuadrant.io/getting-started/ before it landed, and I think there's now less of a need for a follow-on issue. The getting started guide now mentions that the quickstart installs all of Kuadrant locally.
